config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  
  root 'welcome#index', via: :get



  resources :users , except: [:index] do
    resources :requests, only: [:index,:update,:create,:destroy]
    resources :friends, only: [:index,:delete]
    resource :bio , except: [:index], defaults: {format: 'html'}
    resources :search ,only: [:index]
    resource :profile_picture, only: [:new,:create,:destroy]
    resources :activity_feeds, only: [:index]
    resource :security_level, only: [:update]

    resources :photos do 
      resources :comments,only: [:create,:destroy] do 
        resources :likes,only: [:create,:destroy]
      end
      resources :likes,only: [:create,:destroy]
    end

    resources :posts do 
      resources :comments,only: [:create,:destroy] do 
        resources :likes,only: [:create,:destroy]
      end
      resources :likes,only: [:create,:destroy]
    end

    resources :albums do 
      resources :comments,only: [:create,:destroy] do
        resources :likes,only: [:create,:destroy]
      end
      resources :likes, only: [:create,:destroy]
      resources :photos do 
        resources :likes, only: [:create,:destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'  
end

app/views/partials/_accept_friend_request.html.erb
<%= form_tag(user_request_path(current_user,request),method: :put,class: "form-group") do %>
	<%= label_tag "Security Setting :" %>
	<%= select_tag(:reciever_security_setting_id, 
		options_from_collection_for_select(Friendlevel.all, "id", "friendlevel"),class: "form-control") %>
		
	<%= submit_tag "Accept Request", class: "btn btn-success" %>
<% end %>

app/views/partials/_comments.html.erb
<%
	# instanciating the comment post and delete path
	def resource_comment_post_path(user,resource)
		if resource.class.name == "Photo"
			return user_photo_comments_path(user,resource)
		elsif resource.class.name == "Post"
			return user_post_comments_path(user,resource)
		elsif resource.class.name == "Album"
			return user_album_comments_path(user,resource)
		end
	end
	
	def resource_comment_destroy_path(user,resource,comment)
		if resource.class.name == "Photo"
			return user_photo_comment_path(user,resource,comment)
		elsif resource.class.name == "Post"
			return user_post_comment_path(user,resource,comment)
		elsif resource.class.name == "Album"
			return user_album_comment_path(user,resource,comment)
		end
	end	 	 
%>

<!-- displaying all the comments of the resource -->
<% resource.comments.each do |comment| %>


	<section class="application-comment">
		<div class="row">
			
			<section class="col-md-2">
				<%= link_to image_tag(comment.user.profile_picture ? comment.user.profile_picture.picture.url : image_url('defaulthead.png'),style: "width:64px;height:64px;margin: auto;",class: "img img-responsive") , user_path(comment.user) %>
			</section>
			
			<section class="col-md-7">
				<span style="font-weight: bold;font-size: 20px; ">
					<%= comment.user.first_name %>
				</span>
				<span>
					<p style="padding: 0;"><%= comment.body %></p>
				</span> 
			</section>
			<% if resource.user == current_user %>
				<section class="col-md-3">
					<span>
						<%= link_to "Delete",resource_comment_destroy_path(current_user,resource,comment),method: :delete, class: "btn btn-danger"%>
					</span>
				</section>	
			<% end %>
		</div>
	</section>		
<% end %>


<!-- new comment form -->
<div class="application-comment">

	<div class="row">
		<section class="col-md-2">
			<%= link_to image_tag(current_user.profile_picture ? current_user.profile_picture.picture.url : image_url('defaulthead.png'),style: "width:80px;margin:0 auto;",class: "img img-responsive") , user_path(current_user) %>
		</section>
		
		<section class="col-md-10">
			<span style="font-weight: bold;font-size: 20px; ">
						<%= current_user.first_name %>
			</span>
			<span>
				<%= form_tag(resource_comment_post_path(current_user,resource),method:"post" ,name: "comment") do %>
					<textarea style="width: 100%;height: 100%;border-radius: 10px;" type="text" name="body" placeholder="post a comment..."></textarea>
					<%= submit_tag "Post Comment",class: "btn btn-primary",style:"color:Whole;"%>
				<% end %>
				
			</span>
		</section>	
	</div>
</div>

app/views/partials/_security_level.html.erb
<% if current_user.id == params[:user_id].to_i %>
	<%= form_tag(user_security_level_path(current_user),method: :put) do %>

		<%= label_tag "Security Setting :",nil,style: "margin-bottom: 15px;font-size: 21px;font-weight: 200;" %>

		<% if resource.class.name == "User" %>
			<% @selected_id = Friend.new(current_user).getFriendLevel(resource.id).id %>
			<% @securitylevels = Friendlevel.all %>
			<% @value = "friendlevel" %>
			<%= hidden_field_tag :friend_id , resource.id %>
		<% elsif resource.class.name == "Post"%>
			<% @selected_id = Post.find(resource.id).security_setting.securitylevel_id %>
			<%= hidden_field_tag :post_id , resource.id %>
			<% @securitylevels = Securitylevel.all %>
			<% @value = "securitylevel" %>
		<% elsif resource.class.name == "Photo" %>
			<% @selected_id = Photo.find(resource.id).security_setting.securitylevel_id %>
			<%= hidden_field_tag :photo_id , resource.id %>
			<% @securitylevels = Securitylevel.all %>
			<% @value = "securitylevel" %>
		<% elsif resource.class.name == "Album" %>
			<% @selected_id = Album.find(resource.id).security_setting.securitylevel_id %>
			<%= hidden_field_tag :album_id , resource.id %>
			<% @securitylevels = Securitylevel.all %>
			<% @value = "securitylevel" %>
		<% end %>

		<%= select_tag(:securitylevel_id, 
			options_from_collection_for_select(
				@securitylevels,
				"id",
				@value,
				:selected => @selected_id ),
				class: "application-select "
			) %>
		
		<%= submit_tag "Change security level", class: "btn btn-small btn-primary",style: "color:white;margin-top:0;"%>

	<% end %>
<% end %>

app/views/partials/_send_friend_request.html.erb
<%= form_tag(user_requests_path(current_user)) do %>
	<%= label_tag "Security Setting :",nil,style: "margin-bottom: 15px;font-size: 21px;font-weight: 200;" %>
	<%= select_tag(:sender_security_level_id, 
		options_from_collection_for_select(Friendlevel.all, "id", "friendlevel"),class: "application-select") %>

	<%= hidden_field_tag :id, friend.id %>
	<%= submit_tag "Send Friend Request", class: "btn btn-success",style: "color:white;margin-top:0;" %>
<% end %>