config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  
  root 'welcome#index', via: :get



  resources :users , except: [:index] do
    resources :requests, only: [:index,:update,:create,:destroy]
    resources :friends, only: [:index,:delete]
    resource :bio , except: [:index], defaults: {format: 'html'}
    resources :search ,only: [:index]
    resource :profile_picture, only: [:new,:create,:destroy]
    resources :activity_feeds, only: [:index]
    resource :security_level, only: [:update]

    resources :photos do 
      resources :comments,only: [:create,:destroy] do 
        resources :likes,only: [:create,:destroy]
      end
      resources :likes,only: [:create,:destroy]
    end

    resources :posts do 
      resources :comments,only: [:create,:destroy] do 
        resources :likes,only: [:create,:destroy]
      end
      resources :likes,only: [:create,:destroy]
    end

    resources :albums do 
      resources :comments,only: [:create,:destroy] do
        resources :likes,only: [:create,:destroy]
      end
      resources :likes, only: [:create,:destroy]
      resources :photos do 
        resources :likes, only: [:create,:destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'  
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	       :recoverable, :rememberable, :trackable, :validatable
	validates_presence_of :first_name,:last_name,:email
	
	has_many :posts
	has_many :photos
	has_many :albums
	has_many :comments
	has_one :bio
	has_many :activity_feeds
	has_one :profile_picture
	has_many :friend_ships
	has_many :friends, through: :friend_ships, class_name: 'User'

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

 
  # GET /users/1
  # GET /users/1.json
  def show
    @profile = Profile.new(@user)
    @posts = @profile.getPostsForUser(current_user.id)
    @photos = @profile.getPhotosForUser(current_user.id)
    @albums = @profile.getAlbumsForUser(current_user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
  
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if User.where(id: params[:id]).count == 1
        @user = User.find(params[:id])
      else
        flash[:danger] = "Resource Not Found - user not found having the specified user id"
        redirect_to user_path(current_user)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_id,:first_name, :last_name, :bio_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :bio_id %><br>
    <%= f.number_field :bio_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
	
	<div class="row">
		<section class="col-md-4" style="background-color: #333;padding-left:0;padding-right: 0;border-radius: 6px;">

			<img style="margin:0 auto;width: auto;height: 300px;" class="img img-responsive" src="<%= @user.profile_picture ? @user.profile_picture.picture.url : image_url('defaulthead.png') %>">
					
			<% if @user == current_user %> 
				<%= link_to "Change Profile Picture",new_user_profile_picture_path(current_user) , class: "btn btn-primary", style: "width: 100%;border-radius:0;color: white;"%>
				
				<%= link_to "Delete Profile Picture",user_profile_picture_path(current_user),method: :delete, class: "btn btn-danger", style: "width: 100%;border-radius:0 0 6px 6px;color: white;"%>
			<% end %>
		</section>

		<section class="col-md-8">
			<div class="jumbotron">
				<h1	style="font-family: arial;margin-top: 0;">
					<%= @user.first_name %> <%= @user.last_name %>
				</h1>
				<% if @user.bio != nil %>
				   	<p>
						Works At <%= @user.bio.work_place %> as <%= @user.bio.designation%>
					</p>
					<p>
						Studied <%= @user.bio.university_degree %> at <%= @user.bio.university%>
					</p>
					<p>
						Studied <%= @user.bio.college_cert %> at <%= @user.bio.college %>
					</p>
					<p>
						Studied <%= @user.bio.school_cert %> at <%= @user.bio.school %>
					</p>
					<p>
						Home Town : <%= @user.bio.home_town %>
					</p>
				
				<% else %>
					<h3><%= @user.first_name %> has no personal information to show</h3>
				<% end %>
				
				<%= link_to "Edit Bio",edit_user_bio_path(current_user),class: "btn btn-info pull-right",style: "color:white;text-align:center;" if @user == current_user %>
			</div>	
		</section>	
	</div>

	<% if !Friend.new(@user).isFriendOf?(current_user) && @user != current_user && !FriendShip.isSentRequest?(@user.id,current_user.id) %>
		<hr/>
		<%= render "partials/send_friend_request" , friend: @user %>
		<hr/>
	<% elsif FriendShip.isSentRequest?(@user.id,current_user.id) %>
		<button type="button" class="btn btn-info">Friend Request Sent</button>
	<% end %>


	<div>
		<section>
			<% if @posts.count > 0 %>
				<h1>
					<%= @user.first_name %>'s <%= link_to "Posts",user_posts_path(@user) %>
				</h1>
				<% @posts.order("posts.created_at limit 3").each do |post| %>
					<div class="jumbotron">
					    <h1><%= post.title%></h1>
					    <span>created <%= time_ago_in_words post.created_at %> ago</span> | 
					    <span>updated <%= time_ago_in_words post.updated_at %> ago</span>
					    
					    <h2><%= truncate(post.body) %></h2>
					    
					    <%= link_to "View Full Post", user_post_path(@user,post),class: "btn btn-primary",style: "color:white;"%>

					
					    <% if post.user == current_user %>
						    <%= link_to "Edit",edit_user_post_path(current_user,post), class: "btn btn-primary", style: "color: white;" %>
						    <%= link_to "Delete",user_post_path(current_user,post) , method: :delete, class: "btn btn-danger", style: "color: white;" %> 
					    <% end %> 
					    
					</div>
					<hr/>
				<% end %>
			<% else %>
				<h1><%= "#{@user.first_name} has no posts to show" %></h1>
			<% end %>
		</section>
	</div>

	<div>
		<% if @photos.count > 0 %>
		<section class="row">
			<h1>
				<%= @user.first_name %>'s <%= link_to "Photos",user_photos_path(@user) %> 
			</h1>
			
			<% @photos.order("photos.created_at limit 3").each do |photo| %>
				<div class="col-md-4">
					<%= link_to image_tag(photo.picture.url,class: "img img-responsive"),user_photo_path(@user,photo) %>
				</div>
			<% end %>
		</section>
		<% else %>
			<h1><%= "#{@user.first_name} has no photos to show" %></h1>
		
		<% end %>
	</div>

	<hr/>

	<div>
		<% if @albums.count > 0 %>
		<section class="row">		
			<h1>
				<%= @user.first_name %>'s <%= link_to "Albums",user_albums_path(@user) %>
			</h1>
			<% @albums.order("albums.created_at limit 3").each do |album| %>
				<div class="col-md-4">
					<a href="<%= user_album_path(album.user,album) %>">
						<div class="jumbotron">
							<h1><%= album.title %></h1>
							<% if album.photos.count > 0 %>
								<img src="<%= album.photos.first.picture.url %>" class="img-responsive" alt="Album Image">
							<% end %>
							
						</div>
					</a>
					<%= render "partials/security_level" ,resource: album %>
				</div>	
			<% end %>
		</section>
		<% else %>
			<h1><%= "#{@user.first_name} has no albums to show" %></h1>
		<% end %> 
		
	</div>