config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  
  root 'welcome#index', via: :get



  resources :users , except: [:index] do
    resources :requests, only: [:index,:update,:create,:destroy]
    resources :friends, only: [:index,:delete]
    resource :bio , except: [:index], defaults: {format: 'html'}
    resources :search ,only: [:index]
    resource :profile_picture, only: [:new,:create,:destroy]
    resources :activity_feeds, only: [:index]
    resource :security_level, only: [:update]

    resources :photos do 
      resources :comments,only: [:create,:destroy] do 
        resources :likes,only: [:create,:destroy]
      end
      resources :likes,only: [:create,:destroy]
    end

    resources :posts do 
      resources :comments,only: [:create,:destroy] do 
        resources :likes,only: [:create,:destroy]
      end
      resources :likes,only: [:create,:destroy]
    end

    resources :albums do 
      resources :comments,only: [:create,:destroy] do
        resources :likes,only: [:create,:destroy]
      end
      resources :likes, only: [:create,:destroy]
      resources :photos do 
        resources :likes, only: [:create,:destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'  
end

app/models/activity_feed.rb
class ActivityFeed < ActiveRecord::Base
	belongs_to :targetable, polymorphic: true
	belongs_to :user
	belongs_to :securitylevel
	
	validates :securitylevel_id, presence: true
	validates :targetable_id, presence: true
	validates :targetable_type, presence: true
	validates :user_id, presence: true

	after_create_commit :broadcastActivityFeeds

	def broadcastActivityFeeds
		self.users.each do |user|
			# enque the jobs 
			ActivityBroadcastJob.perform_later(user: user,feed: self)
		end 
	end
	
	def users 
		selfSender = FriendShip.where(sender: self.user,state: :done).where("securitylevel1_id <= ?",self.securitylevel_id - 1)
		
		selfReceiever = FriendShip.where(reciever: self.user,state: :done).where("securitylevel2_id <= ?",self.securitylevel_id - 1)
	

		User.where(id: selfSender.select("friends_id")).or(User.where(id: selfReceiever.select("user_id"))).or(User.where(id: self.user_id))
	end

	def getActivityFeeds(user)		
		ActivityFeed.where(user: senders(user)).where("securitylevel_id >= (?)",senderSecurityLevel(user)).or(ActivityFeed.where(user: recievers(user)).where("securitylevel_id >= (?)",recieverSecurityLevel(user))).or(ActivityFeed.where(user: user)).order("created_at DESC")
	end

	def createActivityFeed(user,type,action)
		activity_feed = ActivityFeed.create(targetable_id: type.id,targetable_type: type.class.name,securitylevel_id: type.getSecurityLevel.id,status: action, user: user)
	end

	private

	def senders user
		User.where(id: FriendShip.select(:user_id).where(reciever: user,state: :done))
	end
	
	def recievers user
		User.where(id: FriendShip.select(:friends_id).where(sender: user,state: :done))
	end

	def senderSecurityLevel user
		FriendShip.select("securitylevel1_id + 1").where(sender: Friend.new(user).getAllFriends,reciever:user).limit(1)
	end

	def recieverSecurityLevel user 
		FriendShip.select("securitylevel2_id + 1").where(sender: user,reciever: Friend.new(user).getAllFriends).limit(1)
	end
end

app/controllers/activity_feeds_controller.rb
class ActivityFeedsController < ApplicationController

	respond_to :json,:html

	def index
		if params[:user_id].to_i == current_user.id
			if params.has_key? :since 
				since = DateTime.strptime(params[:since],'%s')
				@activity_feeds = ActivityFeed.new.getActivityFeeds(current_user).where("created_at > ?",since) 
			else
				@activity_feeds = ActivityFeed.new.getActivityFeeds(current_user).limit(10)
			end
			respond_with @activity_feeds
		else
			redirect_to user_activity_feeds_path(current_user)			 
		end
	end

end

app/helpers/activity_feeds_helper.rb
module ActivityFeedsHelper
end

app/views/activity_feeds/_activity_feed.html.erb
<div class="row" style="background-color: #eee;">
	<div class="col-md-2">
    	<%= link_to(activity_feed.user.profile_picture ? image_tag(activity_feed.user.profile_picture.picture.url,class: "img img-responsive",style: "height:100px;margin:30px auto;") : image_tag(image_url('defaulthead.png'),class: "media-object",style: "height:64px;width:64px;margin:20px auto"), user_path(activity_feed.user)) %>	  
	</div>

	<div class="col-md-9">
    	<h4>
				<%= activity_feed.user.first_name %> <%= activity_feed.status %>
				<%= activity_feed.status == "created" ? "a new" : "a" %>
				<%= activity_feed.targetable_type %>
				<% if activity_feed.targetable_type == "Comment" %>
					On 
					<% if activity_feed.targetable.commentable_type == "Post" %>
						<%= link_to activity_feed.targetable.commentable_type, user_post_path(activity_feed.targetable.commentable.user,activity_feed.targetable.commentable),style: "color:blue;text-decoration:underline;"%>
					<% elsif activity_feed.targetable.commentable_type == "Photo" %>
						<%= link_to activity_feed.targetable.commentable_type, user_photo_path(activity_feed.targetable.commentable.user,activity_feed.targetable.commentable),style: "color:blue;text-decoration:underline;"%>
					<% elsif activity_feed.targetable.commentable_type == "Album" %>
						<%= link_to activity_feed.targetable.commentable_type, user_album_path(activity_feed.targetable.commentable.user,activity_feed.targetable.commentable),style: "color:blue;text-decoration:underline;"%>
					<% end %>
					
				<% end %>
			</h4>
	
			<p><%= time_ago_in_words(activity_feed.created_at) %> ago</p>

			<% if activity_feed.targetable_type == "Post" %>

				<h5><strong><%= activity_feed.targetable.title %> </strong>| <%= activity_feed.targetable.body %></h5>

				
				<%= link_to "Show Post",user_post_path(activity_feed.targetable.user,activity_feed.targetable.id) , class: "btn btn-primary",style: "color:white" %>

			<% elsif activity_feed.targetable_type == "Photo" %>

				<%= image_tag(activity_feed.targetable.picture.url, class: "img img-responsive",style: "width: 200px;max-height:300px;margin: 0 auto;")%>
				
				<%= link_to "Show Photo",user_photo_path(activity_feed.targetable.user,activity_feed.targetable_id), class: "btn btn-primary" ,style: "color:white;margin-bottom:20px;"%>

			<% elsif activity_feed.targetable_type == "Album" %>
				
				<%= link_to "Show Album",user_album_path(activity_feed.targetable.user,activity_feed.targetable_id), class: "btn btn-primary",style: "color:white" %>
			
			<% else activity_feed.targetable_type == "Comment" %>
				
				<% if activity_feed.targetable.commentable_type == "Post" %>
					<h6><%= activity_feed.targetable.body %></h6>
					
					<%= link_to "Show Post",user_post_path(activity_feed.targetable.user,activity_feed.targetable_id),class: "btn btn-primary",style: "color:white;" %>

				<% elsif activity_feed.targetable.commentable_type == "Photo" %>
					<h6><%= activity_feed.targetable.body %></h6>
					
					
					<%= link_to "Show Photo",user_post_path(activity_feed.user,activity_feed.targetable_id),class: "btn btn-primary",style: "color:white;" %>

				<% elsif activity_feed.targetable.commentable_type == "Album" %>
					<h6><%= activity_feed.targetable.body %></h6>
					
					<%= link_to "Show Album",user_post_path(activity_feed.user,activity_feed.targetable_id),class: "btn btn-primary",style: "color:white;" %>

				<% end %>

			<% end %>
  	</div>
</div>
<hr/>

app/views/activity_feeds/index.html.erb
<section>
	<div class="row">
		<section class="col-md-6" style="padding-right: 0;">
			<%= link_to "Add Photo", new_user_photo_path(current_user),class: "btn btn-primary",style: "color:white;width:100%;border-radius:0;" %>
		</section>
		<section class="col-md-6" style="padding-left: 0;">
			<%= link_to "Add Album" , new_user_album_path(current_user),class: "btn btn-primary",style: "color:white;width:100%;border-radius:0;" %>
		</section>
	</div>

	<div>
		<%= form_tag(user_posts_path(current_user),class:"form-group") do %>
			<%= fields_for :post do |ff|%>
				<%= ff.text_field :title, class: "form-control", placeholder: "Post Title..."%>
				<%= ff.text_area :body,class: "form-control",placeholder: "Post Body..."%>
				<div class="form-group">
				    <label>Security Setting</label>
				    <select name="securitylevel_id" class="form-control">
					    <% Securitylevel.all.each do |level| %>
					    	<option value="<%= level.id %>"><%= level.securitylevel %></option>
					    <% end %> 
				    </select>
				 </div>
				<%= ff.submit "New Post" ,class: "btn btn-primary",style: "color: white;"%>
			<% end %>
		<% end %>
	</div>	
</section>

<hr/>

<section id="activities">
	<% if @activity_feeds.count > 0 %>
		<% @activity_feeds.each do |activity_feed| %>
			<%= render "activity_feed", activity_feed: activity_feed %> 
		<% end %>
	<% else %>

	<h1>No Activity feeds to show</h1>

	<% end %>
</section> 