config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  
  root 'welcome#index', via: :get



  resources :users , except: [:index] do
    resources :requests, only: [:index,:update,:create,:destroy]
    resources :friends, only: [:index,:delete]
    resource :bio , except: [:index], defaults: {format: 'html'}
    resources :search ,only: [:index]
    resource :profile_picture, only: [:new,:create,:destroy]
    resources :activity_feeds, only: [:index]
    resource :security_level, only: [:update]

    resources :photos do 
      resources :comments,only: [:create,:destroy] do 
        resources :likes,only: [:create,:destroy]
      end
      resources :likes,only: [:create,:destroy]
    end

    resources :posts do 
      resources :comments,only: [:create,:destroy] do 
        resources :likes,only: [:create,:destroy]
      end
      resources :likes,only: [:create,:destroy]
    end

    resources :albums do 
      resources :comments,only: [:create,:destroy] do
        resources :likes,only: [:create,:destroy]
      end
      resources :likes, only: [:create,:destroy]
      resources :photos do 
        resources :likes, only: [:create,:destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'  
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
	has_many :activity_feeds, as: :targetable
	has_one :security_setting, as: :securable
	has_many :likes, as: :likeable

	validates :title, presence: true
	validates :body, presence: true

	def getSecurityLevel
		self.security_setting.securitylevel
	end

	def getPosts(user,friendId = nil)
		if friendId != nil
			if friendId == user.id
				return user.posts
			end  
			if Friend.new(user).isFriendOf?(friendId)  
				return getSecurePosts(user,friendId)
			else 
				return getPublicPosts(user)
			end 
		else
			return user.posts 
		end
	end

	private

	def getPublicPosts user
		Post.where(id: SecuritySetting.select(:securable_id).where(securable: user.posts,securitylevel: Securitylevel.find_by(Securitylevel: "Public")))
	end

	def getSecurePosts(user,friendId)
		Post.where(id: SecuritySetting.select(:securable_id).where(securable: user.posts).where("securitylevel_id >= (?)",Friend.new(user).getFriendLevel(friendId).id + 1))
	end		
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: [:show, :edit, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @profile = Profile.new(@user)
    @posts = @profile.getPostsForUser(current_user.id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.security_setting = SecuritySetting.new
    @post.security_setting.securitylevel = Securitylevel.find(params[:securitylevel_id])

    
    respond_to do |format|
      if @post.save
        ActivityFeed.new.createActivityFeed(current_user,@post,"created")
        format.html { redirect_to user_posts_path(current_user,@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        ActivityFeed.new.createActivityFeed(current_user,@post,"updated")
        @post.security_setting.securitylevel_id = params[:securitylevel_id]
        @post.security_setting.save
        format.html { redirect_to user_post_path(current_user,@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path(current_user), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by(id: params[:id],user_id: params[:user_id])
      if @post == nil
        flash[:danger] = "Resource Desent Exist" 
        redirect_to user_path(current_user)
      end
    end

    def set_user
      if User.where(id: params[:user_id]).count == 1
        @user = User.find(params[:user_id])
      else
        flash[:danger] = "Resource Not Found"
        redirect_to user_posts_path(current_user)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@user,@post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <hr/>
  <div class="field form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body , class: "form-control" %>
  </div>
<hr/>
  <div class="form-group">
    <label>Security Setting</label>
    <select name="securitylevel_id" class="form-control">
      <% Securitylevel.all.each do |level| %>
       <option value="<%= level.id %>"><%= level.securitylevel %></option>
      <% end %> 
    </select>
  </div>
<hr/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', user_post_path(current_user,@post) %> |
<%= link_to 'Back', user_posts_path(current_user) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.first_name %>'s Posts</h1>

<% if @user == current_user %>
	<%= link_to 'New Post', new_user_post_path , class: "btn btn-primary", style: "color: white;" %>
<% end %>

<hr/>

<% @posts.order("posts.created_at desc").each do |post| %>
	<div class="jumbotron">
	    <h1><%= post.title%></h1>
	    <span>created <%= time_ago_in_words post.created_at %> ago</span> | 
	    <span>updated <%= time_ago_in_words post.updated_at %> ago</span>
	    
	    <h2><%= truncate(post.body) %></h2>
	    
	    <%= link_to "View Full Post", user_post_path(@user,post),class: "btn btn-primary",style: "color:white;"%>

	
	    <% if post.user == current_user %>
		    <%= link_to "Edit",edit_user_post_path(current_user,post), class: "btn btn-primary", style: "color: white;" %>
		    <%= link_to "Delete",user_post_path(current_user,post) , method: :delete, class: "btn btn-danger", style: "color: white;" %> 
	    <% end %> 
	    
	</div>
	<hr/> 
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path(current_user) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<section class="jumbotron">
	<h1><%= @post.title %></h1>
	<p><%= @post.body %></p>
	<span>created : <%= time_ago_in_words(@post.created_at) %></span>
</section>

<hr/>

<%= render 'partials/comments' , resource: @post %>

<hr/>

<% if @post.user == current_user %>
	<%= render "partials/security_level" ,resource: @post %>
	<%= link_to 'Edit', edit_user_post_path(current_user,@post) %> |
	<%= link_to 'Back', user_posts_path(current_user) %>
<% end %>